# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_pagescxJvLj.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from qt_core import *


class Ui_MainPages(object):
    def setupUi(self, MainPages):
        if MainPages.objectName():
            MainPages.setObjectName(u"MainPages")
        MainPages.resize(810, 569)
        font = QFont()
        font.setPointSize(8)
        MainPages.setFont(font)
        self.main_pages_layout = QVBoxLayout(MainPages)
        self.main_pages_layout.setSpacing(0)
        self.main_pages_layout.setObjectName(u"main_pages_layout")
        self.main_pages_layout.setContentsMargins(5, 5, 5, 5)
        self.pages = QStackedWidget(MainPages)
        self.pages.setObjectName(u"pages")
        self.page_token = QWidget()
        self.page_token.setObjectName(u"page_token")
        self.page_token.setFont(font)
        self.page_token.setStyleSheet(u"")
        self.verticalLayout_5 = QVBoxLayout(self.page_token)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.scroll_area_3 = QScrollArea(self.page_token)
        self.scroll_area_3.setObjectName(u"scroll_area_3")
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area_3.sizePolicy().hasHeightForWidth())
        self.scroll_area_3.setSizePolicy(sizePolicy)
        self.scroll_area_3.setFont(font)
        self.scroll_area_3.setStyleSheet(u"background: transparent;")
        self.scroll_area_3.setFrameShape(QFrame.NoFrame)
        self.scroll_area_3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_area_3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_area_3.setWidgetResizable(True)
        self.contents_3 = QWidget()
        self.contents_3.setObjectName(u"contents_3")
        self.contents_3.setGeometry(QRect(0, 0, 782, 546))
        self.contents_3.setStyleSheet(u"background: transparent;")
        self.verticalLayout_4 = QVBoxLayout(self.contents_3)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.frame_2 = QFrame(self.contents_3)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setMinimumSize(QSize(0, 50))
        self.frame_2.setMaximumSize(QSize(16777215, 50))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.session_info_layout_2 = QVBoxLayout(self.frame_2)
        self.session_info_layout_2.setSpacing(0)
        self.session_info_layout_2.setObjectName(u"session_info_layout_2")
        self.session_info_layout_2.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_4.addWidget(self.frame_2)

        self.session_frame_2 = QFrame(self.contents_3)
        self.session_frame_2.setObjectName(u"session_frame_2")
        self.session_frame_2.setMinimumSize(QSize(0, 40))
        self.session_frame_2.setMaximumSize(QSize(10000, 40))
        self.session_frame_2.setFrameShape(QFrame.NoFrame)
        self.session_frame_2.setFrameShadow(QFrame.Raised)
        self.gridLayout_7 = QGridLayout(self.session_frame_2)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setHorizontalSpacing(0)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.token_choice = QFrame(self.session_frame_2)
        self.token_choice.setObjectName(u"token_choice")
        self.token_choice.setMinimumSize(QSize(0, 40))
        self.token_choice.setMaximumSize(QSize(500, 40))
        self.token_choice.setContextMenuPolicy(Qt.NoContextMenu)
        self.token_choice.setLayoutDirection(Qt.LeftToRight)
        self.token_choice.setFrameShape(QFrame.NoFrame)
        self.token_choice.setFrameShadow(QFrame.Raised)
        self.token_choice_layout = QHBoxLayout(self.token_choice)
        self.token_choice_layout.setSpacing(0)
        self.token_choice_layout.setObjectName(u"token_choice_layout")
        self.token_choice_layout.setContentsMargins(0, 0, 0, 0)

        self.gridLayout_7.addWidget(self.token_choice, 0, 0, 1, 1)


        self.verticalLayout_4.addWidget(self.session_frame_2)

        self.create_session_button_2 = QFrame(self.contents_3)
        self.create_session_button_2.setObjectName(u"create_session_button_2")
        self.create_session_button_2.setMinimumSize(QSize(0, 150))
        self.create_session_button_2.setMaximumSize(QSize(16777215, 150))
        self.create_session_button_2.setFont(font)
        self.create_session_button_2.setFrameShape(QFrame.NoFrame)
        self.create_session_button_2.setFrameShadow(QFrame.Raised)
        self.gridLayout_8 = QGridLayout(self.create_session_button_2)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.token_create_button = QFrame(self.create_session_button_2)
        self.token_create_button.setObjectName(u"token_create_button")
        self.token_create_button.setMinimumSize(QSize(0, 150))
        self.token_create_button.setMaximumSize(QSize(500, 150))
        self.token_create_button.setFont(font)
        self.token_create_button.setFrameShape(QFrame.NoFrame)
        self.token_create_button.setFrameShadow(QFrame.Raised)
        self.token_create_button_layout = QVBoxLayout(self.token_create_button)
        self.token_create_button_layout.setSpacing(3)
        self.token_create_button_layout.setObjectName(u"token_create_button_layout")
        self.token_create_button_layout.setContentsMargins(0, 0, 0, 0)

        self.gridLayout_8.addWidget(self.token_create_button, 0, 0, 1, 1)


        self.verticalLayout_4.addWidget(self.create_session_button_2)

        self.stop_server_info_frame_3 = QFrame(self.contents_3)
        self.stop_server_info_frame_3.setObjectName(u"stop_server_info_frame_3")
        self.stop_server_info_frame_3.setMinimumSize(QSize(0, 270))
        self.stop_server_info_frame_3.setMaximumSize(QSize(10000, 1000))
        self.stop_server_info_frame_3.setFrameShape(QFrame.NoFrame)
        self.stop_server_info_frame_3.setFrameShadow(QFrame.Raised)
        self.gridLayout_9 = QGridLayout(self.stop_server_info_frame_3)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.gridLayout_9.setContentsMargins(0, 15, 0, 0)
        self.stop_server_buttons_frame_3 = QFrame(self.stop_server_info_frame_3)
        self.stop_server_buttons_frame_3.setObjectName(u"stop_server_buttons_frame_3")
        self.stop_server_buttons_frame_3.setMinimumSize(QSize(500, 270))
        self.stop_server_buttons_frame_3.setMaximumSize(QSize(1000, 4000))
        self.stop_server_buttons_frame_3.setFrameShape(QFrame.NoFrame)
        self.stop_server_buttons_frame_3.setFrameShadow(QFrame.Raised)
        self.token_table_layout = QVBoxLayout(self.stop_server_buttons_frame_3)
        self.token_table_layout.setSpacing(5)
        self.token_table_layout.setObjectName(u"token_table_layout")
        self.token_table_layout.setContentsMargins(0, 0, 0, 0)

        self.gridLayout_9.addWidget(self.stop_server_buttons_frame_3, 0, 0, 1, 1)

        self.verticalSpacer_3 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_9.addItem(self.verticalSpacer_3, 1, 0, 1, 1)


        self.verticalLayout_4.addWidget(self.stop_server_info_frame_3)

        self.scroll_area_3.setWidget(self.contents_3)

        self.verticalLayout_5.addWidget(self.scroll_area_3)

        self.pages.addWidget(self.page_token)
        self.page_server = QWidget()
        self.page_server.setObjectName(u"page_server")
        self.page_1_layout = QVBoxLayout(self.page_server)
        self.page_1_layout.setSpacing(5)
        self.page_1_layout.setObjectName(u"page_1_layout")
        self.page_1_layout.setContentsMargins(5, 5, 5, 5)
        self.scroll_area = QScrollArea(self.page_server)
        self.scroll_area.setObjectName(u"scroll_area")
        sizePolicy.setHeightForWidth(self.scroll_area.sizePolicy().hasHeightForWidth())
        self.scroll_area.setSizePolicy(sizePolicy)
        self.scroll_area.setStyleSheet(u"background: transparent;")
        self.scroll_area.setFrameShape(QFrame.NoFrame)
        self.scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_area.setWidgetResizable(True)
        self.contents = QWidget()
        self.contents.setObjectName(u"contents")
        self.contents.setGeometry(QRect(0, 0, 790, 549))
        self.contents.setStyleSheet(u"background: transparent;")
        self.verticalLayout = QVBoxLayout(self.contents)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.server_frame = QFrame(self.contents)
        self.server_frame.setObjectName(u"server_frame")
        self.server_frame.setMinimumSize(QSize(0, 80))
        self.server_frame.setMaximumSize(QSize(10000, 80))
        self.server_frame.setFrameShape(QFrame.NoFrame)
        self.server_frame.setFrameShadow(QFrame.Raised)
        self.gridLayout = QGridLayout(self.server_frame)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.server_button_frame = QFrame(self.server_frame)
        self.server_button_frame.setObjectName(u"server_button_frame")
        self.server_button_frame.setMinimumSize(QSize(0, 80))
        self.server_button_frame.setMaximumSize(QSize(500, 80))
        self.server_button_frame.setContextMenuPolicy(Qt.NoContextMenu)
        self.server_button_frame.setLayoutDirection(Qt.LeftToRight)
        self.server_button_frame.setFrameShape(QFrame.NoFrame)
        self.server_button_frame.setFrameShadow(QFrame.Raised)
        self.server_layout = QVBoxLayout(self.server_button_frame)
        self.server_layout.setSpacing(3)
        self.server_layout.setObjectName(u"server_layout")
        self.server_layout.setContentsMargins(0, 0, 0, 0)

        self.gridLayout.addWidget(self.server_button_frame, 0, 0, 1, 1)


        self.verticalLayout.addWidget(self.server_frame)

        self.start_server_frame = QFrame(self.contents)
        self.start_server_frame.setObjectName(u"start_server_frame")
        self.start_server_frame.setMinimumSize(QSize(0, 40))
        self.start_server_frame.setMaximumSize(QSize(16777215, 40))
        self.start_server_frame.setFrameShape(QFrame.NoFrame)
        self.start_server_frame.setFrameShadow(QFrame.Raised)
        self.gridLayout_2 = QGridLayout(self.start_server_frame)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.start_server_button_frame = QFrame(self.start_server_frame)
        self.start_server_button_frame.setObjectName(u"start_server_button_frame")
        self.start_server_button_frame.setMinimumSize(QSize(0, 40))
        self.start_server_button_frame.setMaximumSize(QSize(500, 40))
        self.start_server_button_frame.setFrameShape(QFrame.NoFrame)
        self.start_server_button_frame.setFrameShadow(QFrame.Raised)
        self.server_buttons_layout = QHBoxLayout(self.start_server_button_frame)
        self.server_buttons_layout.setSpacing(3)
        self.server_buttons_layout.setObjectName(u"server_buttons_layout")
        self.server_buttons_layout.setContentsMargins(0, 0, 0, 0)

        self.gridLayout_2.addWidget(self.start_server_button_frame, 0, 0, 1, 1)


        self.verticalLayout.addWidget(self.start_server_frame)

        self.stop_server_info_frame = QFrame(self.contents)
        self.stop_server_info_frame.setObjectName(u"stop_server_info_frame")
        self.stop_server_info_frame.setMinimumSize(QSize(0, 120))
        self.stop_server_info_frame.setMaximumSize(QSize(10000, 1000))
        self.stop_server_info_frame.setFrameShape(QFrame.NoFrame)
        self.stop_server_info_frame.setFrameShadow(QFrame.Raised)
        self.gridLayout_3 = QGridLayout(self.stop_server_info_frame)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 15, 0, 0)
        self.stop_server_buttons_frame = QFrame(self.stop_server_info_frame)
        self.stop_server_buttons_frame.setObjectName(u"stop_server_buttons_frame")
        self.stop_server_buttons_frame.setMinimumSize(QSize(500, 40))
        self.stop_server_buttons_frame.setMaximumSize(QSize(500, 4000))
        self.stop_server_buttons_frame.setFrameShape(QFrame.NoFrame)
        self.stop_server_buttons_frame.setFrameShadow(QFrame.Raised)
        self.stop_server_layout = QVBoxLayout(self.stop_server_buttons_frame)
        self.stop_server_layout.setSpacing(5)
        self.stop_server_layout.setObjectName(u"stop_server_layout")
        self.stop_server_layout.setContentsMargins(0, 0, 0, 0)

        self.gridLayout_3.addWidget(self.stop_server_buttons_frame, 0, 0, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_3.addItem(self.verticalSpacer, 1, 0, 1, 1)


        self.verticalLayout.addWidget(self.stop_server_info_frame)

        self.scroll_area.setWidget(self.contents)

        self.page_1_layout.addWidget(self.scroll_area)

        self.pages.addWidget(self.page_server)
        self.page_session = QWidget()
        self.page_session.setObjectName(u"page_session")
        self.page_session.setFont(font)
        self.page_session.setStyleSheet(u"QFrame {\n"
"	font-size: 16pt;\n"
"}")
        self.verticalLayout_3 = QVBoxLayout(self.page_session)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.scroll_area_2 = QScrollArea(self.page_session)
        self.scroll_area_2.setObjectName(u"scroll_area_2")
        sizePolicy.setHeightForWidth(self.scroll_area_2.sizePolicy().hasHeightForWidth())
        self.scroll_area_2.setSizePolicy(sizePolicy)
        self.scroll_area_2.setStyleSheet(u"background: transparent;")
        self.scroll_area_2.setFrameShape(QFrame.NoFrame)
        self.scroll_area_2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_area_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_area_2.setWidgetResizable(True)
        self.contents_2 = QWidget()
        self.contents_2.setObjectName(u"contents_2")
        self.contents_2.setGeometry(QRect(0, 0, 782, 541))
        self.contents_2.setStyleSheet(u"background: transparent;")
        self.verticalLayout_2 = QVBoxLayout(self.contents_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.frame = QFrame(self.contents_2)
        self.frame.setObjectName(u"frame")
        self.frame.setMinimumSize(QSize(0, 50))
        self.frame.setMaximumSize(QSize(16777215, 50))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.session_info_layout = QVBoxLayout(self.frame)
        self.session_info_layout.setSpacing(0)
        self.session_info_layout.setObjectName(u"session_info_layout")
        self.session_info_layout.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_2.addWidget(self.frame)

        self.session_frame = QFrame(self.contents_2)
        self.session_frame.setObjectName(u"session_frame")
        self.session_frame.setMinimumSize(QSize(0, 40))
        self.session_frame.setMaximumSize(QSize(10000, 400))
        self.session_frame.setFrameShape(QFrame.NoFrame)
        self.session_frame.setFrameShadow(QFrame.Raised)
        self.gridLayout_4 = QGridLayout(self.session_frame)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.session_name_frame = QFrame(self.session_frame)
        self.session_name_frame.setObjectName(u"session_name_frame")
        self.session_name_frame.setMinimumSize(QSize(0, 40))
        self.session_name_frame.setMaximumSize(QSize(500, 400))
        self.session_name_frame.setContextMenuPolicy(Qt.NoContextMenu)
        self.session_name_frame.setLayoutDirection(Qt.LeftToRight)
        self.session_name_frame.setFrameShape(QFrame.NoFrame)
        self.session_name_frame.setFrameShadow(QFrame.Raised)
        self.create_session_layout = QVBoxLayout(self.session_name_frame)
        self.create_session_layout.setObjectName(u"create_session_layout")
        self.create_session_layout.setContentsMargins(0, 0, 0, 0)

        self.gridLayout_4.addWidget(self.session_name_frame, 0, 0, 1, 1)


        self.verticalLayout_2.addWidget(self.session_frame)

        self.create_session_button = QFrame(self.contents_2)
        self.create_session_button.setObjectName(u"create_session_button")
        self.create_session_button.setMinimumSize(QSize(0, 100))
        self.create_session_button.setMaximumSize(QSize(16777215, 120))
        self.create_session_button.setFrameShape(QFrame.NoFrame)
        self.create_session_button.setFrameShadow(QFrame.Raised)
        self.gridLayout_5 = QGridLayout(self.create_session_button)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.session_button_frame = QFrame(self.create_session_button)
        self.session_button_frame.setObjectName(u"session_button_frame")
        self.session_button_frame.setMinimumSize(QSize(0, 40))
        self.session_button_frame.setMaximumSize(QSize(500, 40))
        self.session_button_frame.setFrameShape(QFrame.NoFrame)
        self.session_button_frame.setFrameShadow(QFrame.Raised)
        self.load_session_layout = QVBoxLayout(self.session_button_frame)
        self.load_session_layout.setSpacing(6)
        self.load_session_layout.setObjectName(u"load_session_layout")
        self.load_session_layout.setContentsMargins(0, 0, 0, 0)

        self.gridLayout_5.addWidget(self.session_button_frame, 1, 0, 1, 1)

        self.dropdown_menu_session_names = QFrame(self.create_session_button)
        self.dropdown_menu_session_names.setObjectName(u"dropdown_menu_session_names")
        self.dropdown_menu_session_names.setMinimumSize(QSize(0, 55))
        self.dropdown_menu_session_names.setMaximumSize(QSize(500, 55))
        self.dropdown_menu_session_names.setFrameShape(QFrame.StyledPanel)
        self.dropdown_menu_session_names.setFrameShadow(QFrame.Raised)
        self.session_names_dropdown_menu_layout = QVBoxLayout(self.dropdown_menu_session_names)
        self.session_names_dropdown_menu_layout.setObjectName(u"session_names_dropdown_menu_layout")
        self.session_names_dropdown_menu_layout.setContentsMargins(0, 15, 0, 0)

        self.gridLayout_5.addWidget(self.dropdown_menu_session_names, 0, 0, 1, 1)


        self.verticalLayout_2.addWidget(self.create_session_button)

        self.stop_server_info_frame_2 = QFrame(self.contents_2)
        self.stop_server_info_frame_2.setObjectName(u"stop_server_info_frame_2")
        self.stop_server_info_frame_2.setMinimumSize(QSize(0, 120))
        self.stop_server_info_frame_2.setMaximumSize(QSize(10000, 1000))
        self.stop_server_info_frame_2.setFrameShape(QFrame.NoFrame)
        self.stop_server_info_frame_2.setFrameShadow(QFrame.Raised)
        self.gridLayout_6 = QGridLayout(self.stop_server_info_frame_2)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setContentsMargins(0, 15, 0, 0)
        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_6.addItem(self.verticalSpacer_2, 0, 0, 1, 1)


        self.verticalLayout_2.addWidget(self.stop_server_info_frame_2)

        self.scroll_area_2.setWidget(self.contents_2)

        self.verticalLayout_3.addWidget(self.scroll_area_2)

        self.pages.addWidget(self.page_session)
        self.page_message = QWidget()
        self.page_message.setObjectName(u"page_message")
        self.verticalLayout_7 = QVBoxLayout(self.page_message)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.frame_3 = QFrame(self.page_message)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setMinimumSize(QSize(0, 40))
        self.frame_3.setMaximumSize(QSize(10000, 40))
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.gridLayout_10 = QGridLayout(self.frame_3)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.searchbar_frame = QFrame(self.frame_3)
        self.searchbar_frame.setObjectName(u"searchbar_frame")
        self.searchbar_frame.setMinimumSize(QSize(0, 40))
        self.searchbar_frame.setMaximumSize(QSize(500, 40))
        self.searchbar_frame.setContextMenuPolicy(Qt.NoContextMenu)
        self.searchbar_frame.setLayoutDirection(Qt.LeftToRight)
        self.searchbar_frame.setFrameShape(QFrame.NoFrame)
        self.searchbar_frame.setFrameShadow(QFrame.Raised)
        self.searchbar_layout = QVBoxLayout(self.searchbar_frame)
        self.searchbar_layout.setSpacing(3)
        self.searchbar_layout.setObjectName(u"searchbar_layout")
        self.searchbar_layout.setContentsMargins(0, 0, 0, 0)

        self.gridLayout_10.addWidget(self.searchbar_frame, 0, 0, 1, 1)


        self.verticalLayout_7.addWidget(self.frame_3)

        self.start_server_frame_2 = QFrame(self.page_message)
        self.start_server_frame_2.setObjectName(u"start_server_frame_2")
        self.start_server_frame_2.setMinimumSize(QSize(0, 40))
        self.start_server_frame_2.setMaximumSize(QSize(16777215, 40))
        self.start_server_frame_2.setFrameShape(QFrame.NoFrame)
        self.start_server_frame_2.setFrameShadow(QFrame.Raised)
        self.gridLayout_11 = QGridLayout(self.start_server_frame_2)
        self.gridLayout_11.setObjectName(u"gridLayout_11")
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.load_messages_button_frame = QFrame(self.start_server_frame_2)
        self.load_messages_button_frame.setObjectName(u"load_messages_button_frame")
        self.load_messages_button_frame.setMinimumSize(QSize(0, 40))
        self.load_messages_button_frame.setMaximumSize(QSize(500, 40))
        self.load_messages_button_frame.setFrameShape(QFrame.NoFrame)
        self.load_messages_button_frame.setFrameShadow(QFrame.Raised)
        self.load_messages_button_layout = QHBoxLayout(self.load_messages_button_frame)
        self.load_messages_button_layout.setSpacing(3)
        self.load_messages_button_layout.setObjectName(u"load_messages_button_layout")
        self.load_messages_button_layout.setContentsMargins(0, 0, 0, 0)

        self.gridLayout_11.addWidget(self.load_messages_button_frame, 0, 0, 1, 1)


        self.verticalLayout_7.addWidget(self.start_server_frame_2)

        self.scroll_area_4 = QScrollArea(self.page_message)
        self.scroll_area_4.setObjectName(u"scroll_area_4")
        sizePolicy.setHeightForWidth(self.scroll_area_4.sizePolicy().hasHeightForWidth())
        self.scroll_area_4.setSizePolicy(sizePolicy)
        self.scroll_area_4.setStyleSheet(u"background: transparent;")
        self.scroll_area_4.setFrameShape(QFrame.NoFrame)
        self.scroll_area_4.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_area_4.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_area_4.setWidgetResizable(True)
        self.contents_4 = QWidget()
        self.contents_4.setObjectName(u"contents_4")
        self.contents_4.setGeometry(QRect(0, 0, 809, 449))
        self.contents_4.setStyleSheet(u"background: transparent;")
        self.verticalLayout_6 = QVBoxLayout(self.contents_4)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.stop_server_info_frame_4 = QFrame(self.contents_4)
        self.stop_server_info_frame_4.setObjectName(u"stop_server_info_frame_4")
        self.stop_server_info_frame_4.setMinimumSize(QSize(0, 120))
        self.stop_server_info_frame_4.setMaximumSize(QSize(10000, 16777215))
        self.stop_server_info_frame_4.setFrameShape(QFrame.NoFrame)
        self.stop_server_info_frame_4.setFrameShadow(QFrame.Raised)
        self.gridLayout_12 = QGridLayout(self.stop_server_info_frame_4)
        self.gridLayout_12.setObjectName(u"gridLayout_12")
        self.gridLayout_12.setContentsMargins(0, 15, 0, 0)
        self.messages_frame = QFrame(self.stop_server_info_frame_4)
        self.messages_frame.setObjectName(u"messages_frame")
        self.messages_frame.setMinimumSize(QSize(800, 40))
        self.messages_frame.setMaximumSize(QSize(800, 16777215))
        self.messages_frame.setFrameShape(QFrame.NoFrame)
        self.messages_frame.setFrameShadow(QFrame.Raised)
        self.messages_layout = QVBoxLayout(self.messages_frame)
        self.messages_layout.setSpacing(5)
        self.messages_layout.setObjectName(u"messages_layout")
        self.messages_layout.setContentsMargins(0, 0, 0, 0)

        self.gridLayout_12.addWidget(self.messages_frame, 0, 0, 1, 1)

        self.verticalSpacer_4 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_12.addItem(self.verticalSpacer_4, 1, 0, 1, 1)


        self.verticalLayout_6.addWidget(self.stop_server_info_frame_4)

        self.scroll_area_4.setWidget(self.contents_4)

        self.verticalLayout_7.addWidget(self.scroll_area_4)

        self.pages.addWidget(self.page_message)

        self.main_pages_layout.addWidget(self.pages)


        self.retranslateUi(MainPages)

        self.pages.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(MainPages)
    # setupUi

    def retranslateUi(self, MainPages):
        MainPages.setWindowTitle(QCoreApplication.translate("MainPages", u"Form", None))
    # retranslateUi

